-- Migration: Create user_generated_recipes table for AI-generated recipes
-- Stores recipes generated by AI that belong to specific users

-- ============================================
-- USER GENERATED RECIPES TABLE
-- ============================================
CREATE TABLE public.user_generated_recipes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  rating DECIMAL(2,1) DEFAULT 5.0 CHECK (rating >= 0 AND rating <= 5),
  prep_time TEXT,
  cook_time TEXT,
  total_time INTEGER, -- in minutes
  difficulty TEXT CHECK (difficulty IN ('Easy', 'Medium', 'Hard')),
  calories INTEGER,
  protein INTEGER, -- grams
  carbs INTEGER, -- grams
  fat INTEGER, -- grams
  fiber INTEGER, -- grams
  sodium INTEGER, -- mg
  servings INTEGER,
  cuisine TEXT,
  meal_type TEXT,
  -- Store ingredients as JSONB array: [{"name": "...", "quantity": 1, "unit": "cup"}]
  ingredients JSONB DEFAULT '[]',
  -- Store instructions as JSONB array: ["Step 1", "Step 2", ...]
  instructions JSONB DEFAULT '[]',
  -- Structured tags following 2025 best practices (JSONB)
  tags JSONB DEFAULT '{}',
  -- Legacy flat categories for backward compatibility
  categories JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Indexes for faster lookups
CREATE INDEX idx_user_generated_recipes_user_id ON public.user_generated_recipes(user_id);
CREATE INDEX idx_user_generated_recipes_created_at ON public.user_generated_recipes(created_at DESC);
CREATE INDEX idx_user_generated_recipes_cuisine ON public.user_generated_recipes(cuisine);
CREATE INDEX idx_user_generated_recipes_meal_type ON public.user_generated_recipes(meal_type);

-- ============================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================

-- Enable RLS
ALTER TABLE public.user_generated_recipes ENABLE ROW LEVEL SECURITY;

-- Users can only view their own generated recipes
CREATE POLICY "Users can view own generated recipes" ON public.user_generated_recipes
  FOR SELECT USING (auth.uid() = user_id);

-- Users can insert their own generated recipes
CREATE POLICY "Users can insert own generated recipes" ON public.user_generated_recipes
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can update their own generated recipes
CREATE POLICY "Users can update own generated recipes" ON public.user_generated_recipes
  FOR UPDATE USING (auth.uid() = user_id);

-- Users can delete their own generated recipes
CREATE POLICY "Users can delete own generated recipes" ON public.user_generated_recipes
  FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- TRIGGERS
-- ============================================

-- Trigger for updated_at (reuses existing function from migration 005)
CREATE TRIGGER update_user_generated_recipes_updated_at
  BEFORE UPDATE ON public.user_generated_recipes
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
